language: python
python:
  - '3.6'
matrix:
  allow_failures:
    - python: 3.7
  include:
    - python: 3.7
      dist: xenial    # required for Python 3.7 (travis-ci/travis-ci#9069)
      sudo: required  # required for Python 3.7 (travis-ci/travis-ci#9069)

install:
  - make env
script:
  - make test
