language: python
matrix:
  allow_failures:
    - python: 3.6
    - python: 3.7
    - python: 3.8

install:
  - make env
script:
  - make lint
  - make test

# ignore tags build
branches:
  except:
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/

after_success:
  - codecov